### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by thetravellor** [aidengilmartin/speedtest-to-influxdb#11]
Hi There,

Ive set my environment variables up already.
Im using Influx 1.8

If I run this as a normal user I get:

pi@raspberrypi:~/speedtest-to-influxdb $ python3 ./speedtest2influx.py
Info : 10/01/2021 00:40:32 : Speedtest CLI Data Logger to InfluxDB started
Info : 10/01/2021 00:40:32 : DB initialization complete
Traceback (most recent call last):
  File "./speedtest2influx.py", line 127, in <module>
    main()
  File "./speedtest2influx.py", line 107, in main
    data = format_for_influx(speedtest.stdout)
  File "./speedtest2influx.py", line 47, in format_for_influx
    data = json.loads(cliout)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

If I run it as root I get 

pi@raspberrypi:~/speedtest-to-influxdb $ sudo python3 ./speedtest2influx.py
Info : 10/01/2021 00:41:49 : Speedtest CLI Data Logger to InfluxDB started
Error : 10/01/2021 00:41:49 : Unable to get list of databases
Error : 10/01/2021 00:41:49 : DB initialization error

**Comment by aidengilmartin** [comment]
Hi, this sounds like issue #2 & #5. You might not have the right version of Speedtest CLI installed. There is the official one from Ookla and an unofficial (but open source) version available in the Debian repositories. Could you post the output of `speedtest -V`?

No need to run the script as root.

**Comment by thetravellor** [comment]
You were correct, I had a speedest-cli python script with the same name! 

I have corrected that and moved on, and it still errors:

Environment

`pi@raspberrypi:~/speedtest-to-influxdb $ echo $DB_USER
speedtest
pi@raspberrypi:~/speedtest-to-influxdb $ echo $DB_ADDRESS
localhost
pi@raspberrypi:~/speedtest-to-influxdb $ echo $DB_DATABASE
speedtest
pi@raspberrypi:~/speedtest-to-influxdb $ echo $DB_PORT
8086
`
Speedtest:

`pi@raspberrypi:~/speedtest-to-influxdb $ speedtest -V
Speedtest by Ookla 1.0.0.2 (5ae238b) Linux/arm-linux-musleabihf 5.4.72-v7l+ arm/armv7l

The official command line client for testing the speed and performance
of your internet connection.
`

Error:

`pi@raspberrypi:~/speedtest-to-influxdb $ ./speedtest2influx.py
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/360.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/360.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/360.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/360.
from: too many arguments
from: too many arguments
./speedtest2influx.py: line 10: syntax error near unexpected token `('
./speedtest2influx.py: line 10: `DB_ADDRESS = os.environ.get('DB_ADDRESS', 'db_hostname.network')'`

Other things:

pi@raspberrypi:~/speedtest-to-influxdb $ python -V
Python 3.7.3
pi@raspberrypi:~/speedtest-to-influxdb $ python2 -V
Python 2.7.16
pi@raspberrypi:~/speedtest-to-influxdb $ python3 -V
Python 3.7.3
pi@raspberrypi:~/speedtest-to-influxdb $ uname -a
Linux raspberrypi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux

pi@raspberrypi:~/speedtest-to-influxdb $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"


`

**Comment by thetravellor** [comment]
You were correct, it was a confusion with the python based speedtest.cli.

I have renamed the Ookla binary to /usr/local/bin/speedtest-ookla and modified the name of the binary in your script, and can get your script to to by doing

python ./speedtest2influx.py

Is there anyway to set it to run once so it can be run from cron?

**Comment by aidengilmartin** [comment]
Glad you got it sorted, someone else had a similar issue with removing the unofficial speedtest client cleanly. Thanks for the systemd service example too.
