### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by madether** [aidengilmartin/speedtest-to-influxdb#16]
python3 ./speedtest2influx.py
Info : 27/05/2021 21:54:16 : Speedtest CLI Data Logger to InfluxDB started
Info : 27/05/2021 21:54:16 : DB initialization complete
Traceback (most recent call last):
  File "./speedtest3influx.py", line 128, in <module>
    main()
  File "./speedtest3influx.py", line 105, in main
    ["speedtest", "--accept-license", "--accept-gdpr", "-f", "json"], capture_output=True)
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

speedtest -V
Speedtest by Ookla 1.0.0.2 (5ae238b) Linux/x86_64-linux-musl 4.9.0-14-amd64 x86_64

The official command line client for testing the speed and performance
of your internet connection.

**Comment by madether** [comment]
Need to remove capture_output=True, then the traceback occurs.  it does generate out put but it fails to upload to the db
["speedtest", "--accept-license", "--accept-gdpr", "-f", "json"], capture_output=True)


Traceback (most recent call last):
  File "./speedtest3influx.py", line 129, in <module>
    main()
  File "./speedtest3influx.py", line 109, in main
    data = format_for_influx(speedtest.stdout)
  File "./speedtest3influx.py", line 48, in format_for_influx
    data = json.loads(cliout)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'

**Comment by aidengilmartin** [comment]
Hi there, it isn't broken it just requires Python 3.7+.

Please see the below link with a workaround that should work for Python 3.5. I wouldn't copy the full example though as the source has changed since that issue was created.

[Link to fix](https://github.com/aidengilmartin/speedtest-to-influxdb/issues/2#issuecomment-572565976)

Hope that helps.

**Comment by madether** [comment]
I have added the work around and get the following

Info : 28/05/2021 20:31:13 : Speedtest CLI Data Logger to InfluxDB started
Info : 28/05/2021 20:31:13 : DB initialization complete
Traceback (most recent call last):
  File "./speedtest3influx.py", line 130, in <module>
    main()
  File "./speedtest3influx.py", line 110, in main
    data = format_for_influx(speedtest.stdout)
  File "./speedtest3influx.py", line 49, in format_for_influx
    data = json.loads(cliout)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by aidengilmartin** [comment]
Did you get the official Speedtest client from Ookla directly? This script doesn't work with the unofficial version available from distro repositories. Please can you post the output of `speedtest --accept-license --accept-gdpr -f json`

**Comment by madether** [comment]
certainly got it from Ookla directly

speedtest --accept-license --accept-gdpr -f json
{"type":"result","timestamp":"2021-05-28T10:37:50Z","ping":{"jitter":0.091999999999999998,"latency":43.823999999999998},"download":{"bandwidth":37318604,"bytes":400559952,"elapsed":11412},"upload":{"bandwidth":5667737,"bytes":49783688,"elapsed":8915},"packetLoss":0,"isp":"Starlink","interface":{"internalIp":"redact","name":"eth0","macAddr":"redact","isVpn":false,"externalIp":"redact"},"server":{"id":31279,"name":"TasmaNet Pty LTd","location":"Sydney","country":"Australia","host":"speedtest-vds1.tasmanet.com.au","port":8080,"ip":"redact"},"result":{"id":"9da41bfe-9aa3-4e3e-b24f-b9e17462bd7a","url":"https://www.speedtest.net/result/c/9da41bfe-9aa3-4e3e-b24f-b9e17462bd7a"}}
