### ISSUE TITLE
JSONDecodeError when executing script

### ISSUE THREAD

**Issue by LHDrBillion** [aidengilmartin/speedtest-to-influxdb#3]
Dear Aden,

thanks for your great work! This script could be really usefull, as I am always having trouble with the connection at home, so monitoring would be great. 

When I execute the script, I have the following errors:

Traceback (most recent call last):
  File "main.py", line 98, in <module>
    main()
  File "main.py", line 84, in main
    data = format_for_influx(speedtest.stdout)
  File "main.py", line 33, in format_for_influx
    data = json.loads(cliout)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

As I am not very deep in python, I cant really solve the problem. Would be great to get your support here!

**Comment by aidengilmartin** [comment]
Hi there, glad to be of help.

First off could you post the output of `speedtest -V`?

**Comment by LHDrBillion** [comment]
Dear Aden,

thanks a lot for your quick reply. I have installed the wrong version of the speedtest.cli. If you follow the installation instructions on the speedtest-site, it is working correctly. Thanks a lot for that great tool, as I am using iobroker, influx and grafana, it perfectly integrates into the monitoring environment of my house...

Kind greetings,

Philipp
