### ISSUE TITLE
Error when run

### ISSUE THREAD

**Issue by cristianmenghi** [aidengilmartin/speedtest-to-influxdb#4]
Hi, im testing your script

Speedtest CLI Data Logger to InfluxDB
Traceback (most recent call last):
  File "./main.py", line 100, in <module>
    main()
  File "./main.py", line 83, in main
    ["speedtest", "--json"], capture_output=True)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

speedtest-cli 2.1.2
Python 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

**Comment by aidengilmartin** [comment]
Hey, I'm pretty certain this is a Python version issue. My system and the Docker container are on Python 3.7+.

Someone else had the same issue, have a look at the workaround. I should probably make it the default.
https://github.com/aidengilmartin/speedtest-to-influxdb/issues/2#issuecomment-572565976

Do let me know if that doesn't fix it, thanks.

**Comment by ConnorPlaysYT** [comment]
I am also getting the same error message, any advise?

**Comment by aidengilmartin** [comment]
Does the fix I linked to not work? I can't test at the moment but that would appear to be the solution.
