### ISSUE TITLE
Decode Error

### ISSUE THREAD

**Issue by Stybyk** [aidengilmartin/speedtest-to-influxdb#5]
Hello, 
I am trying to run this script on my RPI3 B+
First, I had a problem completely recognize influxdb module in python.

```
 $ sudo python3 main.py

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from influxdb import InfluxDBClient
ModuleNotFoundError: No module named 'influxdb'
```
That problem is  resolved by : python3 -m pip install influxdb 
But now I´ve got some parser errors. 

```
 $ python3 ./main.py
Speedtest CLI Data Logger to InfluxDB
Traceback (most recent call last):
  File "./main.py", line 98, in <module>
    main()
  File "./main.py", line 84, in main
    data = format_for_influx(speedtest.stdout)
  File "./main.py", line 33, in format_for_influx
    data = json.loads(cliout)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I never make some code in python, do you have any idea where is the problem? 
The script is untouched I changed only parameters for DB for my configuration:

DB_ADDRESS = '10.10.10.240'
DB_PORT = 8086
DB_USER = 'speedtest_usr'
DB_PASSWORD = 'test!'
DB_DATABASE = 'speedtest_db'` 

```
pi@raspberrypi:~ $ python -V
Python 2.7.16
pi@raspberrypi:~ $ python3 -V
Python 3.7.3
```

**Comment by aidengilmartin** [comment]
Hey, could you post the output of `speedtest --accept-license --accept-gdpr -f json`?
You will need to wait a bit as there is no progress indicator with these settings.

Also, a someone else had a decode error like this because they were using the unofficial Speedtest client from the Debian repositories not the official one available only from the Ookla website. Do you have the right one installed?

Thanks.

**Comment by Stybyk** [comment]
Hi,
when i tried to run : speedtest --accept-license --accept-gdpr -f json it told me that command not exist.
So I tried to uninstall speedtest and reinstall again ( Ookla website manual from your link).  Then I discovered, I have some mystic version from python itself.  Because even when I again uninstalled app speedtest still worked :O Help command told me what the stuff it is: 

`$ speedtest -h
usage: speedtest [-h] [--no-download] [--no-upload] [--single] [--bytes]
                 [--share] [--simple] [--csv] [--csv-delimiter CSV_DELIMITER]
                 [--csv-header] [--json] [--list] [--server SERVER]
                 [--exclude EXCLUDE] [--mini MINI] [--source SOURCE]
                 [--timeout TIMEOUT] [--secure] [--no-pre-allocate]
                 [--version]

Command line interface for testing internet bandwidth using speedtest.net.
https://github.com/sivel/speedtest-cli
`

So Ookla speedtest is always ignored and prefered this one.  But how i can get it out ?

**Comment by Stybyk** [comment]
Ok, resolved

``
$ sudo pip uninstall speedtest-cli
Uninstalling speedtest-cli-2.1.2:
  Would remove:
    /usr/local/bin/speedtest
    /usr/local/bin/speedtest-cli
    /usr/local/lib/python2.7/dist-packages/speedtest.py
    /usr/local/lib/python2.7/dist-packages/speedtest_cli-2.1.2.dist-info/*
    /usr/local/lib/python2.7/dist-packages/speedtest_cli.py
Proceed (y/n)? y
  Successfully uninstalled speedtest-cli-2.1.2


$ python3 ./main.py 
Speedtest CLI Data Logger to InfluxDB
Speedtest Successful:
Data written to DB successfully

``

**Comment by aidengilmartin** [comment]
Great, glad you got it sorted.
