### ISSUE TITLE
rc.local doesn´t writes to database 

### ISSUE THREAD

**Issue by Stybyk** [aidengilmartin/speedtest-to-influxdb#7]
How do you run this script in startup and in the background? 

Standard manual run works well..

But when tried usuall startup script with /etc/rc.local
python3 /home/pi/main.py & > /home/pi/Desktop/log.txt 2>&1

I see network utilization on the router´s interface graph, but database data are empty.

**Comment by aidengilmartin** [comment]
What user is the script being run as with your startup script?

If you installed the Python influxDB package with pip you may have run pip as your shell user and thus the package is only available to that user. If this is the case maybe try installing the Python influxDB package with the system package manager (`sudo apt install python3-influxdb`)

I'd also try the startup script without the redirection so the command would be `python3 /home/pi/main.py`.
The script runs the `speedtest` command and reads data written to `stdout` which I think you may be redirecting in your script.

**Comment by Stybyk** [comment]
Yes, probably some problem with that stdout. 
/etc/rc.local is run directly ba system so user is root.
sudo apt install python3-influxdb already installed..

I tried a lot of combinations, with or without output redirection and with and without & 

It looks like that script runs only once after startup and then stays stuck.  
You didn´t run it this style (background and startup)  ? 

Maybe modify it to run one time and then use cron ?

**Comment by Stybyk** [comment]
As I understand,  all data are formatted and managed via CLI outputs..  
And when I run via rc.local, it is working from speed test side, but It can´t work with data output, becase rc.local doesn´t open some terminal.  Can we use another way of data management ?

**Comment by aidengilmartin** [comment]
Ah ok. I personally used this in a Docker container as per the Dockerfile in the repo. Maybe you could try using a systemd service?
[https://www.raspberrypi-spy.co.uk/2015/10/how-to-autorun-a-python-script-on-boot-using-systemd/](https://www.raspberrypi-spy.co.uk/2015/10/how-to-autorun-a-python-script-on-boot-using-systemd/)

**Comment by Stybyk** [comment]
New findings discovered right now: 

python3 /home/pi/main.py & > /home/pi/Desktop/log.txt 2>&1 
(this version of rc.local what i found in manuals doesn´t redirect any output for your script) 

I changed it to: 
sudo python3 /home/pi/main.py > tmp/speedtest.log 2>&1 & 
and then I´ve got proper errors !! Which explained why speed test run only once. 


`
Traceback` (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x759e12f0>: Failed to establish a new connection: [Errno 111] Connection refused

The script is running faster than the docker starting database. Failed connection crashed the whole script. 
So something like a database connection verify test is needed. 

If the connection test fail: sleep for 1 minute or something like that...

**Comment by aidengilmartin** [comment]
That makes sense. If you are using Docker for your DB and the script you can make a running database a dependency for the script. Anyway, I've made the script a little more robust in this respect. Again I'd be grateful if you could give it a quick test before I commit.

```import time
import json
import subprocess

from influxdb import InfluxDBClient

# InfluxDB Settings
DB_ADDRESS = 'db_hostname.network'
DB_PORT = 8086
DB_USER = 'db_username'
DB_PASSWORD = 'db_password'
DB_DATABASE = 'speedtest_db'
DB_RETRY_INVERVAL = 60 # Time before retrying a failed data upload.

# Speedtest Settings
TEST_INTERVAL = 1800  # Time between tests (in seconds).
TEST_FAIL_INTERVAL = 60  # Time before retrying a failed Speedtest (in seconds).

influxdb_client = InfluxDBClient(
    DB_ADDRESS, DB_PORT, DB_USER, DB_PASSWORD, None)


def init_db():
    try:
        databases = influxdb_client.get_list_database()
    except:
        print("Error: Unable to get list of databases")
        raise RuntimeError("No DB connection") from error
    else:
        if len(list(filter(lambda x: x['name'] == DB_DATABASE, databases))) == 0:
            influxdb_client.create_database(
                DB_DATABASE)  # Create if does not exist.
        else:
            influxdb_client.switch_database(DB_DATABASE)  # Switch to if does exist.


def format_for_influx(cliout):
    data = json.loads(cliout)
    # There is additional data in the speedtest-cli output but it is likely not necessary to store.
    influx_data = [
        {
            'measurement': 'ping',
            'time': data['timestamp'],
            'fields': {
                'jitter': float(data['ping']['jitter']),
                'latency': float(data['ping']['latency'])
            }
        },
        {
            'measurement': 'download',
            'time': data['timestamp'],
            'fields': {
                # Byte to Megabit
                'bandwidth': data['download']['bandwidth'] / 125000,
                'bytes': data['download']['bytes'],
                'elapsed': data['download']['elapsed']
            }
        },
        {
            'measurement': 'upload',
            'time': data['timestamp'],
            'fields': {
                # Byte to Megabit
                'bandwidth': data['upload']['bandwidth'] / 125000,
                'bytes': data['upload']['bytes'],
                'elapsed': data['upload']['elapsed']
            }
        },
        {
            'measurement': 'packetLoss',
            'time': data['timestamp'],
            'fields': {
                'packetLoss': float(data['packetLoss'])
            }
        }
    ]
            
    return influx_data


def main():
    db_initialized = False
    
    while(db_initialized == False): 
        try:
            init_db()  # Setup the database if it does not already exist.
        except:
            print("Error: DB initialization error")
            time.sleep(DB_RETRY_INVERVAL)
        else:
            print("Info: DB initialization complete")
            db_initialized = True
        
        
    while (1):  # Run a Speedtest and send the results to influxDB indefinitely.
        speedtest = subprocess.run(
            ["speedtest", "--accept-license", "--accept-gdpr", "-f", "json"], capture_output=True)

        if speedtest.returncode == 0:  # Speedtest was successful.
            data = format_for_influx(speedtest.stdout)
            print("Info: Speedtest successful")
            try:
                if influxdb_client.write_points(data) == True:
                    print("Info: Data written to DB successfully")
                    time.sleep(TEST_INTERVAL)
            except:
                print("Error: Data write to DB failed")
                time.sleep(TEST_FAIL_INTERVAL)
        else:  # Speedtest failed.
            print("Error: Speedtest failed")
            print(speedtest.stderr)
            print(speedtest.stdout)
            time.sleep(TEST_FAIL_INTERVAL)


if __name__ == '__main__':
    print('Speedtest CLI Data Logger to InfluxDB')
    main()
```

**Comment by Stybyk** [comment]
Yes, the script survived the reboot 👍 and still measuring.  GREAT !!!

**Comment by aidengilmartin** [comment]
Nice, thanks for testing that out. I've pushed the changes.
